
name: Build
on: [push]
jobs:

  build-and-deploy-forum-api:
    
    name: Build Docker image of forum API and deploy 
    runs-on: ubuntu-latest
    # needs: forum-api-test
    # env:
    #   AZURE_WEBAPP_NAME: <your-app-name>
    #   GHCR_USERNAME: ${{ github.actor }}
    #   GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    permissions:
      contents: read
      packages: write
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t fitness-planner-forum .
      with:
        context: .
        build-args: AZURE_SQL_CONNECTIONSTRING=${{ secrets.AZURE_SQL_CONNECTIONSTRING }}  
      
      
    - name: Run PyTest
      run: docker run fitness-planner-forum pytest app_test.py

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/brian-mak/fitness-planner-forum:latest
        build-args: AZURE_SQL_CONNECTIONSTRING=${{ secrets.AZURE_SQL_CONNECTIONSTRING }}  
      
    # - name: Azure login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Restart Azure Container
    #   run: |
    #     az container restart --name $AZURE_WEBAPP_NAME --resource-group <your-resource-group-name>
  
